name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish CPM.cmake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set CPM version by tag
        run: sed "s/CURRENT_CPM_VERSION 0.0.0/CURRENT_CPM_VERSION ${GITHUB_REF/refs\/tags\/v}/g" cmake/CPM.cmake > CPM.cmake

      - name: Upload CPM.cmake to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CPM.cmake
          asset_name: CPM.cmake
          tag: ${{ github.ref }}
          overwrite: true
